apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "lighthouse-agent.name" . }}
  namespace: {{ include "lighthouse-agent.namespace" . }}
  labels:
    app.kubernetes.io/component: {{ include "lighthouse-agent.name" . }}
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: {{ include "lighthouse-agent.name" . }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/component: {{ include "lighthouse-agent.name" . }}
    spec:
      containers:
        - image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          name: lighthouse-agent
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP