apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lighthouse-agent.name" . }}
  namespace: {{ include "lighthouse-agent.namespace" . }}
  labels:
    app.kubernetes.io/component: {{ include "lighthouse-agent.name" . }}
data:
  API_TOKEN: {{ .Values.apiToken | toString | b64enc | quote}}